name: Install Nim
description: Installs Nim and adds nim/nimble to the PATH
author: iffy
branding:
  icon: download
  color: yellow
inputs:
  version:
    default: stable

runs:
  using: composite
  steps:
  - name: Install Nim
    shell: bash
    run: |
      export SHELL=/bin/bash
      "${GITHUB_ACTION_PATH}/install-nim.sh" '${{ inputs.version }}'
